#!/usr/bin/env python
#-*- coding: utf-8 -*-

from __future__ import print_function

try:
    input = raw_input
except NameError:
    pass

get_input = input("Please enter string: ")

text = list(get_input)

binary = []

for letters in text:
    binary.append(bin(ord(letters))[2:].zfill(8))

print("".join(binary))